import { toCamelCase, toSchemaName } from './naming.js';
import type { ColumnInfo, TableMap } from '../types.js';

export function convertColType(
  udtName: string,
  columnInfo: { column_default: string | null; is_nullable: string }
): string {
  const hasDefault = columnInfo.column_default;
  const isNullable = columnInfo.is_nullable === 'YES';

  const wrap = (t: string): string => {
    return hasDefault || isNullable ? `Type.Optional(${t})` : t;
  };

  switch (udtName) {
    case 'uuid':
      return wrap("Type.String({format: 'uuid'})");
    case 'bool':
      return wrap('Type.Boolean()');
    case 'float4':
    case 'float8':
    case 'numeric':
      return wrap('Type.Number()');
    case 'int2':
    case 'int4':
    case 'int8':
      return wrap('Type.Integer()');
    case 'varchar':
    case 'text':
    case 'char':
    case 'bpchar':
      return wrap('Type.String()');
    case 'timestamptz':
    case 'timestamp':
      return wrap('Type.String()');
    case 'date':
      return wrap("Type.String({format: 'date'})");
    case 'time':
      return wrap('Type.String()');
    case 'jsonb':
    case 'json':
      return wrap('Type.Any()');
    case '_varchar':
    case '_text':
      return wrap('Type.Array(Type.String())');
    case '_int2':
    case '_int4':
    case '_int8':
      return wrap('Type.Array(Type.Integer())');
    case '_float4':
    case '_float8':
      return wrap('Type.Array(Type.Number())');
    default:
      if (udtName.substring(0, 3) === 'int') {
        return wrap('Type.Integer()');
      }
      return wrap('Type.String()');
  }
}

export function buildTableMap(rows: ColumnInfo[]): TableMap {
  return rows.reduce<TableMap>((acc, row) => {
    const schemaName = toSchemaName(row.table_name);

    if (!acc[schemaName]) {
      acc[schemaName] = {
        name: row.table_name,
        fields: {},
      };
    }

    acc[schemaName].fields[toCamelCase(row.column_name)] = convertColType(
      row.udt_name,
      row
    );

    return acc;
  }, {});
}

export function generateSchemaFile(
  schemaName: string,
  tableName: string,
  fields: Record<string, string>
): string {
  const fieldsStr = JSON.stringify(fields, null, 2).replace(
    /"(.*?)"\s*:\s*"Type(.*?)"/g,
    '$1: Type$2'
  );

  return `// Auto-generated by fastify-auto-sqlapi. Do not edit.
import { Type, Static } from "@sinclair/typebox";
import { toUnderscore } from "fastify-auto-sqlapi";

const _Schema = ${fieldsStr};

const validation = Type.Object(_Schema, { $id: "${schemaName}" });
const partialValidation = Type.Object(
  Object.fromEntries(
    Object.keys(_Schema).map((k) => [
      k,
      validation.required?.includes(k) ? Type.Optional(_Schema[k]) : _Schema[k],
    ])
  ),
  { additionalProperties: false, $id: "Partial${schemaName}" }
);

export const Schema = {
  col: (f: keyof typeof _Schema) => toUnderscore(f),
  fields: _Schema,
  validation,
  tableName: "${tableName}",
  partialValidation,
};
export const ${schemaName} = Schema;
export type TypeSchema = Static<typeof Schema.validation>;
export type Type${schemaName} = TypeSchema;
export default async function (fastify: any) {
  fastify.addSchema(partialValidation);
  fastify.addSchema(validation);
}
`;
}
