// this is autogenerated by 'npm run schema:generate'
import {Type, Static} from "@sinclair/typebox";
import {toUnderscore} from "./util"
const _Schema = {
  id: Type.Number(),
  name: Type.Optional(Type.String()),
  taxNumber: Type.Optional(Type.String()),
  fiscalCode: Type.Optional(Type.String()),
  legalName: Type.Optional(Type.String()),
  address: Type.Optional(Type.String()),
  city: Type.Optional(Type.String()),
  province: Type.Optional(Type.String()),
  cap: Type.Optional(Type.String()),
  invoiceEmail: Type.Optional(Type.String()),
  pec: Type.Optional(Type.String()),
  email: Type.Optional(Type.String()),
  phoneNumber: Type.Optional(Type.String()),
  createdAt: Type.Optional(Type.String()),
  updatedAt: Type.Optional(Type.String()),
  updatedBy: Type.Optional(Type.Number())
};
const validation = Type.Object(_Schema, {$id: "SchemaCustomer"});
const partialValidation = Type.Object(Object.fromEntries(Object.keys(_Schema).map((k)=>[k, validation.required?.includes(k)? Type.Optional(_Schema[k]): _Schema[k]])), {additionalProperties: false, $id: "PartialSchemaCustomer"})
export const Schema = {col: (f:keyof typeof _Schema)=> toUnderscore(f), fields: _Schema, validation, tableName: "customer", partialValidation};
export const SchemaCustomer = Schema;
export type TypeSchema = Static<typeof Schema.validation>;
export type TypeSchemaCustomer = TypeSchema;
export default async function(fastify) {
  fastify.addSchema(partialValidation);
  fastify.addSchema(validation);
}
