/**
 * Generates docs/INDEX.md — the map of what already exists in src/.
 *
 * Indexes *declarations*, not re-exports: src/index.ts is a barrel of ~130 re-exports, so
 * listing those would describe the same symbols twice and hide the internals, which is
 * exactly where duplication happens. Symbols reachable from the barrel are marked `*`.
 *
 * Run: npm run index        Check (CI): npm run index:check
 */
import { Project, Node, type SourceFile, type ExportedDeclarations } from 'ts-morph';
import { writeFileSync, readFileSync } from 'node:fs';
import { relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT = `${ROOT}docs/INDEX.md`;
const SIGNATURE_BUDGET = 90;

type Entry = { name: string; kind: string; signature: string; doc: string; isPublic: boolean };

const project = new Project({ tsConfigFilePath: `${ROOT}tsconfig.json` });

/** Names re-exported by the barrel — the package's public surface. */
function publicNames(): Set<string> {
  const barrel = project.getSourceFile(`${ROOT}src/index.ts`);
  return new Set(barrel ? [...barrel.getExportedDeclarations().keys()] : []);
}

function kindOf(decl: ExportedDeclarations): string {
  if (Node.isFunctionDeclaration(decl)) return 'function';
  if (Node.isClassDeclaration(decl)) return 'class';
  if (Node.isInterfaceDeclaration(decl)) return 'interface';
  if (Node.isTypeAliasDeclaration(decl)) return 'type';
  if (Node.isEnumDeclaration(decl)) return 'enum';
  if (Node.isVariableDeclaration(decl)) return 'const';
  return 'export';
}

/** One-line signature: parameters and return type for callables, the type otherwise. */
function signatureOf(decl: ExportedDeclarations, name: string): string {
  let sig: string;
  if (Node.isFunctionDeclaration(decl) || Node.isMethodDeclaration(decl)) {
    const params = decl.getParameters().map((p) => p.getText()).join(', ');
    sig = `${name}(${params}): ${decl.getReturnTypeNode()?.getText() ?? '…'}`;
  } else if (Node.isClassDeclaration(decl) || Node.isInterfaceDeclaration(decl)) {
    sig = name;
  } else if (Node.isTypeAliasDeclaration(decl)) {
    sig = `${name} = ${decl.getTypeNode()?.getText() ?? '…'}`;
  } else {
    sig = name;
  }
  sig = sig.replace(/\s+/g, ' ').trim();
  return sig.length > SIGNATURE_BUDGET ? `${sig.slice(0, SIGNATURE_BUDGET - 1)}…` : sig;
}

/** First sentence of the TSDoc, if any. */
function docOf(decl: ExportedDeclarations): string {
  if (!Node.isJSDocable(decl)) return '';
  const text = decl.getJsDocs().at(0)?.getDescription() ?? '';
  const first = text.replace(/\s+/g, ' ').trim().split(/(?<=\.)\s/)[0] ?? '';
  return first.length > 100 ? `${first.slice(0, 99)}…` : first;
}

function collect(file: SourceFile, isPublic: (n: string) => boolean): Entry[] {
  const entries: Entry[] = [];
  for (const [name, decls] of file.getExportedDeclarations()) {
    const decl = decls[0];
    if (!decl) continue;
    // Skip symbols declared elsewhere: they belong to their defining module.
    if (decl.getSourceFile().getFilePath() !== file.getFilePath()) continue;
    entries.push({
      name,
      kind: kindOf(decl),
      signature: signatureOf(decl, name),
      doc: docOf(decl),
      isPublic: isPublic(name),
    });
  }
  return entries.sort((a, b) => a.name.localeCompare(b.name));
}

function render(): string {
  const exported = publicNames();
  const files = project
    .getSourceFiles('src/**/*.ts')
    .filter((f) => !f.getFilePath().endsWith('/src/index.ts'))
    .sort((a, b) => a.getFilePath().localeCompare(b.getFilePath()));

  // Deliberately dense: no blank lines, no module grouping (the path already carries it).
  // This file is read by agents with a full context window, and it must stay well under
  // ~300 lines to be worth loading at all.
  const body: string[] = [];
  let total = 0;

  for (const file of files) {
    const path = relative(ROOT, file.getFilePath());
    const entries = collect(file, (n) => exported.has(n));
    if (entries.length === 0) continue;
    total += entries.length;
    body.push(`### ${path}`);
    for (const e of entries) {
      const kind = e.isPublic ? `${e.kind}, public` : e.kind;
      const doc = e.doc ? ` — ${e.doc}` : '';
      body.push(`- \`${e.signature}\` *${kind}*${doc}`);
    }
  }

  return [
    '# Index',
    '',
    `Generated by \`npm run index\` — do not edit. ${total} declarations in ${files.length} files.`,
    '`public` = re-exported from `src/index.ts`, so it is part of the npm API surface.',
    'Search before writing: `npm run find-similar -- "<what you need>"`.',
    '',
    ...body,
    '',
  ].join('\n');
}

const content = render();

if (process.argv.includes('--check')) {
  const current = (() => {
    try {
      return readFileSync(OUT, 'utf8');
    } catch {
      return '';
    }
  })();
  if (current !== content) {
    process.stderr.write('docs/INDEX.md is out of date. Run `npm run index`.\n');
    process.exit(1);
  }
  process.stdout.write('docs/INDEX.md is up to date.\n');
} else {
  writeFileSync(OUT, content);
  process.stdout.write(`Wrote ${relative(ROOT, OUT)} (${content.split('\n').length} lines).\n`);
}
