import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');

const { parseSchemaFile, detectRelations, generateTablesFile, generateSingleTableFile, generateDbTablesIndex } = await import(
  path.join(ROOT, 'dist/lib/cli/tables-codegen.js')
);

// ─── Fixtures ────────────────────────────────────────────────

const customerSchemaContent = `// Auto-generated by fastify-auto-sqlapi. Do not edit.
import { Type, Static } from "@sinclair/typebox";
import { toUnderscore } from "fastify-auto-sqlapi";

const _Schema = {
  id: Type.Optional(Type.Integer()),
  name: Type.String(),
  email: Type.Optional(Type.String())
};

const validation = Type.Object(_Schema, { $id: "SchemaCustomer" });
const partialValidation = Type.Object({}, { additionalProperties: false, $id: "PartialSchemaCustomer" });

export const Schema = {
  col: (f: keyof typeof _Schema) => toUnderscore(f),
  fields: _Schema,
  validation,
  tableName: "customer",
  partialValidation,
};
export const SchemaCustomer = Schema;
export type TypeSchema = Static<typeof Schema.validation>;
`;

const orderSchemaContent = `// Auto-generated
import { Type, Static } from "@sinclair/typebox";
import { toUnderscore } from "fastify-auto-sqlapi";

const _Schema = {
  id: Type.Optional(Type.Integer()),
  customerId: Type.Integer(),
  total: Type.Number(),
  status: Type.Optional(Type.String())
};

const validation = Type.Object(_Schema, { $id: "SchemaCustomerOrder" });
const partialValidation = Type.Object({}, { $id: "PartialSchemaCustomerOrder" });

export const Schema = {
  col: (f: keyof typeof _Schema) => toUnderscore(f),
  fields: _Schema,
  validation,
  tableName: "customer_order",
  partialValidation,
};
export const SchemaCustomerOrder = Schema;
`;

// ─── parseSchemaFile ─────────────────────────────────────────

describe('parseSchemaFile', () => {
  it('extracts schemaName, tableName, fields from schema content', () => {
    const result = parseSchemaFile(customerSchemaContent);
    assert.equal(result.schemaName, 'SchemaCustomer');
    assert.equal(result.tableName, 'customer');
    assert.deepEqual(result.fields, ['id', 'name', 'email']);
  });

  it('extracts field types', () => {
    const result = parseSchemaFile(customerSchemaContent);
    assert.equal(result.fieldTypes.id, 'Type.Optional(Type.Integer())');
    assert.equal(result.fieldTypes.name, 'Type.String()');
    assert.equal(result.fieldTypes.email, 'Type.Optional(Type.String())');
  });

  it('returns null for invalid content', () => {
    assert.equal(parseSchemaFile('not a schema file'), null);
    assert.equal(parseSchemaFile('const _Schema = {};'), null);
  });

  it('parses order schema with FK field', () => {
    const result = parseSchemaFile(orderSchemaContent);
    assert.equal(result.schemaName, 'SchemaCustomerOrder');
    assert.equal(result.tableName, 'customer_order');
    assert.ok(result.fields.includes('customerId'));
  });
});

// ─── detectRelations ─────────────────────────────────────────

describe('detectRelations', () => {
  it('detects FK from field ending with Id', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const order = parseSchemaFile(orderSchemaContent);
    const relations = detectRelations([customer, order]);

    assert.equal(relations.length, 1);
    assert.equal(relations[0].parentSchemaName, 'SchemaCustomer');
    assert.equal(relations[0].parentField, 'id');
    assert.equal(relations[0].childSchemaName, 'SchemaCustomerOrder');
    assert.equal(relations[0].childField, 'customerId');
  });

  it('returns empty when no FK matches', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const relations = detectRelations([customer]);
    assert.equal(relations.length, 0);
  });
});

// ─── generateTablesFile ──────────────────────────────────────

describe('generateTablesFile', () => {
  it('generates valid template with imports and defineTable', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const order = parseSchemaFile(orderSchemaContent);
    const output = generateTablesFile([customer, order]);

    assert.ok(output.includes("import { SchemaCustomer } from './SchemaCustomer.js'"));
    assert.ok(output.includes("import { SchemaCustomerOrder } from './SchemaCustomerOrder.js'"));
    assert.ok(output.includes("const TableCustomer = defineTable({"));
    assert.ok(output.includes("const TableCustomerOrder = defineTable({"));
    assert.ok(output.includes("primary: 'id'"));
    assert.ok(output.includes("export const dbTables: DbTables"));
    assert.ok(output.includes("customer: TableCustomer"));
    assert.ok(output.includes("customer_order: TableCustomerOrder"));
  });

  it('includes auto-detected relation as commented suggestion', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const order = parseSchemaFile(orderSchemaContent);
    const output = generateTablesFile([customer, order]);

    assert.ok(output.includes("buildRelation(SchemaCustomer, 'id', SchemaCustomerOrder, 'customerId')"));
  });

  it('adds excludeFromCreation for auto-increment PK', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateTablesFile([customer]);

    assert.ok(output.includes("excludeFromCreation: ['id']"));
  });

  it('includes defineTable reference in header comment', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateTablesFile([customer]);

    assert.ok(output.includes('defineTable() keys:'));
    assert.ok(output.includes('extraFilters + extendedCondition:'));
  });

  it('lists fields in comment per table', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateTablesFile([customer]);

    assert.ok(output.includes('// Fields: id, name, email'));
  });

  it('includes tenantScope reference in header comment', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateTablesFile([customer]);

    assert.ok(output.includes("tenantScope?"));
    assert.ok(output.includes("tenantScope (direct"));
    assert.ok(output.includes("tenantScope (indirect"));
  });

  it('suggests direct tenantScope for root tables', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateTablesFile([customer]);

    assert.ok(output.includes("// tenantScope: { column: 'tenant_col' },"));
  });

  it('suggests indirect tenantScope for child tables', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const order = parseSchemaFile(orderSchemaContent);
    const output = generateTablesFile([customer, order]);

    assert.ok(output.includes("// tenantScope: { column: 'tenant_col', through: { schema: SchemaCustomer, localField: 'customerId', foreignField: 'id' } },"));
  });
});

// ─── generateSingleTableFile ────────────────────────────────

describe('generateSingleTableFile', () => {
  it('generates file with import, defineTable, and export default', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateSingleTableFile(customer, [customer]);

    assert.ok(output.includes("from 'fastify-auto-sqlapi'"));
    assert.ok(output.includes("import { SchemaCustomer } from '../schemas/SchemaCustomer.js'"));
    assert.ok(output.includes("const TableCustomer = defineTable({"));
    assert.ok(output.includes("primary: 'id'"));
    assert.ok(output.includes("...exportTableInfo(SchemaCustomer)"));
    assert.ok(output.includes("export default TableCustomer;"));
  });

  it('includes excludeFromCreation for auto-increment PK', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateSingleTableFile(customer, [customer]);

    assert.ok(output.includes("excludeFromCreation: ['id']"));
  });

  it('includes fields comment', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateSingleTableFile(customer, [customer]);

    assert.ok(output.includes('// Fields: id, name, email'));
  });

  it('includes header doc link', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateSingleTableFile(customer, [customer]);

    assert.ok(output.includes('defineTable() docs:'));
  });

  it('includes commented relation imports for parent table', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const order = parseSchemaFile(orderSchemaContent);
    const output = generateSingleTableFile(customer, [customer, order]);

    // Customer is parent — relation references SchemaCustomerOrder
    assert.ok(output.includes("// import { SchemaCustomerOrder } from '../schemas/SchemaCustomerOrder.js'"));
  });

  it('includes commented relation imports for child table', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const order = parseSchemaFile(orderSchemaContent);
    const output = generateSingleTableFile(order, [customer, order]);

    // Order is child — relation references SchemaCustomer
    assert.ok(output.includes("// import { SchemaCustomer } from '../schemas/SchemaCustomer.js'"));
  });

  it('includes buildRelation comment for parent table with children', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const order = parseSchemaFile(orderSchemaContent);
    const output = generateSingleTableFile(customer, [customer, order]);

    assert.ok(output.includes("buildRelation(SchemaCustomer, 'id', SchemaCustomerOrder, 'customerId')"));
  });

  it('suggests direct tenantScope for root table', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateSingleTableFile(customer, [customer]);

    assert.ok(output.includes("// tenantScope: { column: 'tenant_col' },"));
  });

  it('suggests indirect tenantScope for child table', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const order = parseSchemaFile(orderSchemaContent);
    const output = generateSingleTableFile(order, [customer, order]);

    assert.ok(output.includes("// tenantScope: { column: 'tenant_col', through: { schema: SchemaCustomer, localField: 'customerId', foreignField: 'id' } },"));
  });
});

// ─── generateDbTablesIndex ──────────────────────────────────

describe('generateDbTablesIndex', () => {
  it('generates import and export for all tables', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const order = parseSchemaFile(orderSchemaContent);
    const output = generateDbTablesIndex([customer, order]);

    assert.ok(output.includes("import TableCustomer from './TableCustomer.js'"));
    assert.ok(output.includes("import TableCustomerOrder from './TableCustomerOrder.js'"));
    assert.ok(output.includes("export const dbTables: DbTables = {"));
    assert.ok(output.includes("customer: TableCustomer,"));
    assert.ok(output.includes("customer_order: TableCustomerOrder,"));
  });

  it('imports DbTables type from fastify-auto-sqlapi', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateDbTablesIndex([customer]);

    assert.ok(output.includes("import type { DbTables } from 'fastify-auto-sqlapi'"));
  });

  it('generates correct output for single table', () => {
    const customer = parseSchemaFile(customerSchemaContent);
    const output = generateDbTablesIndex([customer]);

    assert.ok(output.includes("import TableCustomer from './TableCustomer.js'"));
    assert.ok(output.includes("customer: TableCustomer,"));
    // Should not include other tables
    assert.ok(!output.includes('TableCustomerOrder'));
  });
});
