import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

// generate-tables only reads Schema*.ts files — no database needed.

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const CLI_PATH = path.join(ROOT, 'dist/bin/generate-tables.js');

function schemaFixture(schemaName, tableName, fieldLines) {
  return `// Auto-generated by fastify-auto-sqlapi. Do not edit.
import { Type, Static } from "@sinclair/typebox";
import { toUnderscore } from "fastify-auto-sqlapi";

const _Schema = {
${fieldLines}
};

const validation = Type.Object(_Schema, { $id: "${schemaName}" });
const partialValidation = Type.Object({}, { $id: "Partial${schemaName}" });

export const Schema = {
  col: (f) => toUnderscore(f),
  fields: _Schema,
  validation,
  tableName: "${tableName}",
  partialValidation,
};
export const ${schemaName} = Schema;
`;
}

function runCli(cwd, args) {
  return execFileSync('node', [CLI_PATH, ...args], { cwd, encoding: 'utf-8' });
}

describe('CLI generate-tables with a subset of tables', () => {
  let tmpDir;
  let tablesDir;

  before(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'sqlapi-gen-tables-'));
    const schemasDir = path.join(tmpDir, 'schemas');
    tablesDir = path.join(tmpDir, 'tables');
    fs.mkdirSync(schemasDir, { recursive: true });

    fs.writeFileSync(
      path.join(tmpDir, 'sqlapi.config.js'),
      `export default { outputDir: ${JSON.stringify(tmpDir)} };\n`
    );
    fs.writeFileSync(
      path.join(schemasDir, 'SchemaCustomer.ts'),
      schemaFixture('SchemaCustomer', 'customer',
        '  id: Type.Optional(Type.Integer()),\n  name: Type.String()')
    );
    fs.writeFileSync(
      path.join(schemasDir, 'SchemaProduct.ts'),
      schemaFixture('SchemaProduct', 'product',
        '  id: Type.Optional(Type.Integer()),\n  title: Type.String()')
    );
  });

  after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('dbTables.ts only references Table files that actually exist', () => {
    runCli(tmpDir, ['customer']);

    assert.ok(fs.existsSync(path.join(tablesDir, 'TableCustomer.ts')));
    assert.ok(!fs.existsSync(path.join(tablesDir, 'TableProduct.ts')),
      'TableProduct.ts must not be generated for a subset run');

    const index = fs.readFileSync(path.join(tablesDir, 'dbTables.ts'), 'utf-8');
    assert.ok(index.includes('TableCustomer'), 'index must include the generated table');
    assert.ok(!index.includes('TableProduct'),
      'index must not import a Table file that was never generated');
  });

  it('hints how to update an existing dbTables.ts when new tables are generated', () => {
    const output = runCli(tmpDir, ['product']);

    assert.ok(fs.existsSync(path.join(tablesDir, 'TableProduct.ts')));

    // dbTables.ts is never overwritten once it exists (it may be customized)...
    const index = fs.readFileSync(path.join(tablesDir, 'dbTables.ts'), 'utf-8');
    assert.ok(!index.includes('TableProduct'));
    // ...but the CLI must tell the user what to add
    assert.ok(/TableProduct/.test(output),
      `output should mention the entry to add to dbTables.ts, got:\n${output}`);
  });

  it('--all with no pre-existing index references every table', () => {
    fs.rmSync(path.join(tablesDir, 'dbTables.ts'));
    runCli(tmpDir, ['--all']);

    const index = fs.readFileSync(path.join(tablesDir, 'dbTables.ts'), 'utf-8');
    assert.ok(index.includes('TableCustomer'));
    assert.ok(index.includes('TableProduct'));
  });
});
